on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: Updates youtube videos

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Ultimos Videos da QACademy
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: YOUTUBE
        feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCzsGhfwdImeKj2AOoN92hFw"          